version: '3.9'
services:
  script:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    container_name: sbv2-tool-01
    tty: true
    environment:
      gpus: 'all'
    volumes:
      - ./volumes/inputs:/volumes/inputs
      - ./volumes/outpus:/volumes/outputs
    logging:
      options:
        max-size: '200k'
        max-file: '10'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
